"""
API endpoints for data profiling reports
"""
from fastapi import APIRouter, HTTPException, Path
from app.jobs.store import job_store
from app.utils.logger import logger

router = APIRouter(prefix="/profile", tags=["profile"])


@router.get("/{job_id}")
async def get_profile(job_id: str = Path(..., description="Job ID")):
    """
    Get data profile report (HTML format)
    
    Returns HTML profile generated by ydata-profiling of cleaned/processed data
    """
    try:
        job = job_store.get_job(job_id)
        if not job:
            raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
        
        # Check if job is still processing
        if job.status.value in ["pending", "processing"]:
            raise HTTPException(
                status_code=202,
                detail=f"Job is still {job.status.value}. Profile will be available when job completes. Current progress: {job.progress * 100:.1f}%"
            )
        
        # Check if job failed
        if job.status.value == "failed":
            raise HTTPException(
                status_code=500,
                detail="Job failed. Profile not generated. Check /errors/{job_id} for details."
            )
        
        # Job is completed, check for profile
        if not job.metadata.get("clean_profile_path"):
            raise HTTPException(
                status_code=404, 
                detail="Profile not generated. This may happen if profiling step failed during processing."
            )
        
        report_path = job.metadata["clean_profile_path"]
        
        # Read HTML report
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                content = f.read()
        except FileNotFoundError:
            raise HTTPException(status_code=404, detail="Profile report file not found on disk")
        
        logger.info(f"Retrieved profile for job {job_id}")
        
        return {
            "job_id": job_id,
            "report_path": report_path,
            "content_type": "text/html",
            "content": content
        }
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving profile: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
