"""
API endpoints for data profiling reports
"""
from fastapi import APIRouter, HTTPException, Path, Depends
from fastapi.responses import FileResponse
import os
from app.jobs.store import job_store
from app.guards.appwrite_auth import verify_appwrite_session
from app.utils.logger import logger
from app.utils.job_utils import get_job_with_fallback

router = APIRouter(prefix="/profile", tags=["profile"])


@router.get("/{job_id}")
async def get_profile(
    job_id: str = Path(..., description="Job ID"),
    user: dict = Depends(verify_appwrite_session)
):
    """
    Get data profile report (HTML format)
    
    Returns HTML profile generated by ydata-profiling of cleaned/processed data
    """
    try:
        job = await get_job_with_fallback(job_id)
        if not job:
            raise HTTPException(status_code=404, detail=f"Job {job_id} not found")
        
        # Verify ownership
        if job.user_id != user["$id"]:
            raise HTTPException(
                status_code=403,
                detail="You do not have permission to access this job"
            )
        
        # Check if job is still processing
        if job.status.value in ["pending", "processing"]:
            raise HTTPException(
                status_code=202,
                detail=f"Job is still {job.status.value}. Profile will be available when job completes. Current progress: {job.progress * 100:.1f}%"
            )
        
        # Check if job failed
        if job.status.value == "failed":
            raise HTTPException(
                status_code=500,
                detail="Job failed. Profile not generated. Check /errors/{job_id} for details."
            )
        
        # Job is completed, check for profile
        if not job.metadata.get("clean_profile_path"):
            raise HTTPException(
                status_code=404, 
                detail="Profile not generated. This may happen if profiling step failed during processing."
            )
        
        report_path = job.metadata["clean_profile_path"]
        
        if not os.path.exists(report_path):
            raise HTTPException(status_code=404, detail="Profile report file not found on disk")
        
        logger.info(f"Retrieved profile for job {job_id}")
        
        return FileResponse(
            path=report_path,
            media_type="text/html",
            filename=f"{job_id}_profile.html"
        )
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving profile: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
